#pragma once

// This file is generated by Generate_Textures.py
#include <string_view>

namespace TextureKeys {
    inline constexpr std::string_view Sofia_Crawling_2Frame = "Sofia_Crawling_2Frame";
    inline constexpr std::string_view Mega_Dad_Sheet = "Mega_Dad_Sheet";
    inline constexpr std::string_view Dad_Sprite_Sheet = "Dad_Sprite_Sheet";
    inline constexpr std::string_view Sofia_Sprite_Sheet = "Sofia_Sprite_Sheet";
    inline constexpr std::string_view Dad_Funkier = "Dad_Funkier";
    inline constexpr std::string_view Soother_Item_2Frame = "Soother_Item_2Frame";
    inline constexpr std::string_view Soother = "Soother";
    inline constexpr std::string_view Sofia_Soother_2Frame = "Sofia_Soother_2Frame";
    inline constexpr std::string_view Transparent_Soother = "Transparent_Soother";
    inline constexpr std::string_view background = "background";
    inline constexpr std::string_view Dad_Work = "Dad_Work";
    inline constexpr std::string_view Sprite_Sheet_Crawling = "Sprite_Sheet_Crawling";
    inline constexpr std::string_view Sofia_Soother_Added = "Sofia_Soother_Added";
    inline constexpr std::string_view Crawling_Sofia = "Crawling_Sofia";
    inline constexpr std::string_view Crawling_Sofia_Orig = "Crawling_Sofia_Orig";
}
