#pragma once

// This file is generated by Generate_Textures.py
// Do not edit this file manually
#include <string_view>

namespace TextureKeys {
    inline constexpr const char* Sofia_Crawling_2Frame = "Sofia_Crawling_2Frame";
    inline constexpr const char* Mega_Dad_Sheet = "Mega_Dad_Sheet";
    inline constexpr const char* Dad_Sprite_Sheet = "Dad_Sprite_Sheet";
    inline constexpr const char* Sofia_Sprite_Sheet = "Sofia_Sprite_Sheet";
    inline constexpr const char* Dad_Funkier = "Dad_Funkier";
    inline constexpr const char* Soother_Item_2Frame = "Soother_Item_2Frame";
    inline constexpr const char* Soother = "Soother";
    inline constexpr const char* Sofia_Soother_2Frame = "Sofia_Soother_2Frame";
    inline constexpr const char* Transparent_Soother = "Transparent_Soother";
    inline constexpr const char* background = "background";
    inline constexpr const char* Dad_Work = "Dad_Work";
    inline constexpr const char* Sprite_Sheet_Crawling = "Sprite_Sheet_Crawling";
    inline constexpr const char* Sofia_Soother_Added = "Sofia_Soother_Added";
    inline constexpr const char* Crawling_Sofia = "Crawling_Sofia";
    inline constexpr const char* Crawling_Sofia_Orig = "Crawling_Sofia_Orig";
}
